//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶類別
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶類別()
        {
            this.客戶資料 = new HashSet<客戶資料>();
        }
    
        public int 分類Id { get; set; }
        public string 客戶分類 { get; set; }
        public bool isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶資料> 客戶資料 { get; set; }
        public virtual 客戶類別 客戶類別1 { get; set; }
        public virtual 客戶類別 客戶類別2 { get; set; }
    }
}
